### PR TITLE
Add support of deleted and reproducable recordings

### PR DESCRIPTION
**Pull request by AlwinEsch**
This change add support to plugin for undelete of recordings.

Due to add of new stream functions is it backword compatible to other KODI addons.

Related undelete Pull Request:
KODI: https://github.com/xbmc/xbmc/pull/6326
Addons: https://github.com/opdenkamp/xbmc-pvr-addons/pull/427

### CODE REVIEW

**Comment by FernetMenta** [comment]
see comment on addon. yo need to bump vnsi protocol. older versions of the server need to work with later versions of the addon

**Comment by AlwinEsch** [comment]
Is updated now with check on addon side, several parts was missing from me (Version), Sorry. Thanks for your comment.

**Comment by FernetMenta** [comment]
looks ok. should I press the button?

**Comment by AlwinEsch** [comment]
Is on addons also OK? There was something about WMC. Want to bring this together with addons.

**Comment by AlwinEsch** [comment]
Sorry three pull requests with nearly the same name, here is OK :-D

**Pull request merged**
