### PR TITLE
Update channel scan to newest wirbelscan plugin interface

### PR DESCRIPTION
**Pull request by AlwinEsch**
This changes update the scan control of wirbelscan to his newest version.

This change need also changes on KODI VNSI add-on and inside KODI itself to fix several faults. Is added here for review and to merge in after finish of other changes.

### CODE REVIEW

**Comment by FernetMenta** [comment]
looks ok. did you test this branch with Helix?

**Comment by AlwinEsch** [comment]
I check now with it on Helix.
Has done also a small change there on "cVNSIStatus::Action(void)" to inhibit updates during scan time. Problem currently is on wirbelscan that new channels have on begin not all id's which brings problems for the send new channels, this reduce the amount a bit, but also on KODI is a fix needed otherwise is the PVR database not usable anymore after scan and KODI's restart.

**Comment by AlwinEsch** [comment]
Is checked now on 14.1 and works for playback, for channel search are also changes on XBMC 14.2 and related addon needed.

**Comment by FernetMenta** [comment]
that's fine. merge at your will

**Pull request merged**
